import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Auto-generated by Convex — do not lint
    "convex/_generated/**",
    // Auto-generated by fumadocs (via next.config.mjs source loader) — do not lint
    ".source/**",
  ]),
  {
    rules: {
      // React Compiler is stricter than the manual memoization and ref usage
      // this codebase predates. These three rules report "the compiler skipped
      // this component" — a missed optimization, not a defect — and the fixes
      // change when components recompute or re-render, which needs a browser
      // pass rather than a lint pass. Keep them visible as warnings until that
      // happens. `react-hooks/rules-of-hooks` stays an error: calling hooks
      // conditionally is a real bug, not a missed optimization.
      "react-hooks/preserve-manual-memoization": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/set-state-in-effect": "warn",
    },
  },
]);

export default eslintConfig;
